2025-09-06 02:41:18,842 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-5305' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at C:\Users\Wanda.JN\Downloads\putrial\Skripsi_dashboard\venv\Lib\site-packages\tornado\websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\Users\HP\Downloads\putrial\Skripsi_dashboard\venv\Lib\site-packages\tornado\websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Downloads\putrial\Skripsi_dashboard\venv\Lib\site-packages\tornado\websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
